"use client";

import { useEffect, useMemo, useState } from "react";
import { Home, Trophy, Target, Dog, Clock3, CheckCircle2, BookOpen, PackageCheck, BarChart3, PawPrint, GraduationCap, PlayCircle, Lock, Footprints, Settings } from "lucide-react";
import { challenges as fallbackChallenges, Challenge } from "../data/challenges";
import { supabase, supabaseConfigurationError } from "../lib/supabase";
import Timer from "../components/Timer";

type Screen = "home" | "challenges" | "skills" | "weekly" | "ranking" | "profile" | "lexicon";
type ChallengeStatus = "todo" | "success" | "retry";
type StatusMap = Record<number, ChallengeStatus>;
type AppChallenge = Challenge & { imageUrl?: string|null; videoUrl?: string|null };
type HandlerSkill = { id:number; level:number; title:string; description:string; objective:string; practice:string[]; success:string[]; videoUrl?:string|null };
type SiteSettings = { app_name:string; tagline:string; hero_text:string; hero_image_url:string|null; logo_url:string|null; primary_color:string; secondary_color:string; accent_color:string };
const categories = ["Intérieur", "Extérieur", "Lieu public"] as const;
const fallbackSettings:SiteSettings={app_name:"Sniff and Fun Challenge",tagline:"Défi de détection d’odeurs pour chiens.",hero_text:"Des défis progressifs, simples et motivants à pratiquer à la maison avec votre chien.",hero_image_url:null,logo_url:null,primary_color:"#0a3d12",secondary_color:"#119647",accent_color:"#ffcb05"};

export default function DynamicPage(){
  const [screen,setScreen]=useState<Screen>("home");
  const [challenges,setChallenges]=useState<AppChallenge[]>(fallbackChallenges);
  const [skills,setSkills]=useState<HandlerSkill[]>([]);
  const [settings,setSettings]=useState<SiteSettings>(fallbackSettings);
  const [selected,setSelected]=useState<AppChallenge|null>(null);
  const [selectedSkill,setSelectedSkill]=useState<HandlerSkill|null>(null);
  const [statuses,setStatuses]=useState<StatusMap>(()=>Object.fromEntries(fallbackChallenges.map(c=>[c.id,"todo"])) as StatusMap);
  const [source,setSource]=useState<"supabase"|"fallback"|"error">("fallback");

  useEffect(()=>{if(!supabase){setSource("error");console.error(supabaseConfigurationError);return}(async()=>{
    const [{data:challengeRows,error:challengeError},{data:skillRows,error:skillError},{data:siteRow}] = await Promise.all([
      supabase.from("challenges").select("*").eq("published",true).order("sort_order"),
      supabase.from("handler_skills").select("*").eq("published",true).order("sort_order"),
      supabase.from("site_settings").select("*").eq("id",1).single()
    ]);
    if(siteRow)setSettings(siteRow as SiteSettings);
    if(!challengeError && challengeRows){
      const mapped:AppChallenge[]=challengeRows.map((row:any)=>({id:Number(row.id),title:row.title,category:row.category,level:row.level,description:row.description,duration:row.duration_seconds,completed:false,objective:row.objective,materials:row.materials||[],installation:row.installation||[],steps:row.steps||[],successCriteria:row.success_criteria||[],imageUrl:row.image_url,videoUrl:row.video_url}));
      setChallenges(mapped); setStatuses(current=>Object.fromEntries(mapped.map(c=>[c.id,current[c.id]||"todo"])) as StatusMap); setSource("supabase");
    }
    if(challengeError){setSource("error");console.error("Impossible de charger les défis Supabase",challengeError.message)}
    if(!skillError && skillRows)setSkills(skillRows.map((row:any)=>({id:Number(row.id),level:row.level,title:row.title,description:row.description,objective:row.objective,practice:row.practice||[],success:row.success_criteria||[],videoUrl:row.video_url})));
  })();},[]);

  const total=challenges.length;
  const completed=Object.values(statuses).filter(s=>s==="success").length;
  const progress=total?Math.round(completed/total*100):0;
  const grouped=useMemo(()=>categories.map(category=>({category,items:challenges.filter(c=>c.category===category)})),[challenges]);
  const go=(next:Screen)=>{setScreen(next);setSelected(null);setSelectedSkill(null)};
  const changeStatus=(id:number,status:ChallengeStatus)=>setStatuses(s=>({...s,[id]:status}));
  const themeStyle={"--green-dark":settings.primary_color,"--green":settings.secondary_color,"--gold":settings.accent_color} as React.CSSProperties;

  return <main className="shell" style={themeStyle}>
    <aside className="sidebar"><div className="brand-block">{settings.logo_url?<img src={settings.logo_url} alt={settings.app_name} className="sidebar-logo"/>:<div className="hero-brand-name" style={{fontSize:22,color:settings.primary_color,background:"#fff",padding:10,borderRadius:12}}>{settings.app_name}</div>}</div><nav>
      <Nav active={screen==="home"} onClick={()=>go("home")} icon={<Home size={19}/>} label="Accueil"/><Nav active={screen==="challenges"} onClick={()=>go("challenges")} icon={<Trophy size={19}/>} label="Défis"/><Nav active={screen==="skills"} onClick={()=>go("skills")} icon={<GraduationCap size={19}/>} label="Compétences conducteur"/><Nav active={screen==="weekly"} onClick={()=>go("weekly")} icon={<Target size={19}/>} label="Défi hebdomadaire"/><Nav active={screen==="ranking"} onClick={()=>go("ranking")} icon={<BarChart3 size={19}/>} label="Progression"/><Nav active={screen==="lexicon"} onClick={()=>go("lexicon")} icon={<BookOpen size={19}/>} label="Lexique"/><Nav active={screen==="profile"} onClick={()=>go("profile")} icon={<Dog size={19}/>} label="Profil"/>
      <a className="nav-btn" href="/admin"><Settings size={19}/><span>Administration</span></a>
    </nav><div className="sidebar-profile"><div className="avatar">🐕</div><div><strong>Nova</strong><span>Niveau 1</span></div><div className="mini-progress"><span style={{width:`${progress}%`}}/></div></div></aside>
    <section className="content">{selected?<ChallengeDetail challenge={selected} status={statuses[selected.id]||"todo"} onStatus={s=>changeStatus(selected.id,s)} onBack={()=>setSelected(null)}/>:selectedSkill?<SkillDetail skill={selectedSkill} onBack={()=>setSelectedSkill(null)}/>:screen==="home"?<HomeScreen settings={settings} challenges={challenges} completed={completed} total={total} progress={progress} statuses={statuses} source={source} onChallenges={()=>go("challenges")} onSelect={setSelected}/>:screen==="challenges"?<ChallengesScreen grouped={grouped} statuses={statuses} onSelect={setSelected}/>:screen==="skills"?<SkillsScreen skills={skills} onSelect={setSelectedSkill}/>:screen==="ranking"?<ProgressScreen progress={progress} completed={completed} total={total} statuses={statuses}/>:screen==="lexicon"?<LexiconScreen/>:screen==="weekly"?<SimpleHeader eyebrow="CETTE SEMAINE" title="Défi hebdomadaire · Niveau 1" text="Trois recherches à compléter pour participer au classement."/>:<ProfileScreen/>}</section>
  </main>;
}

function Nav({active,onClick,icon,label}:any){return <button className={`nav-btn ${active?"active":""}`} onClick={onClick}>{icon}<span>{label}</span></button>}
function HomeScreen({settings,challenges,completed,total,progress,statuses,source,onChallenges,onSelect}:any){const featured=challenges.slice(0,2);const heroStyle=settings.hero_image_url?{backgroundImage:`linear-gradient(90deg,rgba(10,61,18,.88),rgba(10,61,18,.22)),url(${settings.hero_image_url})`,backgroundSize:"cover",backgroundPosition:"center"}:undefined;return <div className="dashboard"><section className="brand-hero sniff-fun-hero" style={heroStyle}><div className="hero-copy"><div className="hero-brand-name">{settings.app_name}</div><h1>{settings.tagline}</h1><p>{settings.hero_text}</p><button className="accent-button" onClick={onChallenges}>Commencer un défi</button></div></section><section className="welcome-strip"><div className="welcome-icon"><PawPrint size={28}/></div><div><h2>Bonjour !</h2><p>Prêt pour une nouvelle aventure olfactive avec votre chien ?</p><small>Données : {source==="supabase"?"Supabase connecté":source==="error"?"Supabase indisponible — données de secours":"mode de secours"}</small></div></section><div className="dashboard-grid"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">À PRATIQUER</p><h2>Défis disponibles</h2></div></div><div className="featured-grid">{featured.map((c:AppChallenge)=><article className="featured-card" key={c.id}><div className={`featured-image image-${c.id}`} style={c.imageUrl?{backgroundImage:`url(${c.imageUrl})`}:undefined}><span>NIVEAU {c.level}</span></div><div className="featured-body"><h3>{c.title}</h3><p>{c.description}</p><div className="featured-footer"><span><Trophy size={16}/>{statusLabel(statuses[c.id])}</span><button className="accent-button small" onClick={()=>onSelect(c)}>Commencer</button></div></div></article>)}</div></section><section className="panel"><h2>Ma progression</h2><div className="progress-layout"><div className="progress-ring" style={{"--pct":`${progress*3.6}deg`} as React.CSSProperties}><div><small>NIVEAU</small><strong>1</strong><span>{completed}/{total} défis</span></div></div><div className="progress-list"><p><Trophy size={18}/><span>Défis réussis</span><strong>{completed}</strong></p><p><CheckCircle2 size={18}/><span>Progression</span><strong>{progress}%</strong></p></div></div></section></div></div>}
function ChallengesScreen({grouped,statuses,onSelect}:any){return <><SimpleHeader eyebrow="NIVEAU 1" title="Mes défis" text="Complète toutes les catégories pour débloquer le niveau suivant."/>{grouped.map((g:any)=><section className="category-section" key={g.category}><h2>{g.category}</h2><div className="challenge-grid">{g.items.map((c:AppChallenge)=><button className={`challenge-card challenge-${statuses[c.id]}`} key={c.id} onClick={()=>onSelect(c)} style={c.imageUrl?{backgroundImage:`url(${c.imageUrl})`}:undefined}><div className="challenge-top"><span className="number">{c.id}</span><span className="status">{statusLabel(statuses[c.id])}</span></div><h3>{c.title}</h3><p>{c.description}</p><small>{formatDuration(c.duration)} max</small></button>)}</div></section>)}</>}
function ChallengeDetail({challenge,status,onStatus,onBack}:{challenge:AppChallenge,status:ChallengeStatus,onStatus:(s:ChallengeStatus)=>void,onBack:()=>void}){return <><button className="back" onClick={onBack}>← Retour aux défis</button><div className="detail-card">{challenge.imageUrl&&<img src={challenge.imageUrl} alt={challenge.title} style={{width:"100%",maxHeight:360,objectFit:"cover",borderRadius:14,marginBottom:22}}/>}<div className="detail-heading"><div><span className="pill">{challenge.category} · Niveau {challenge.level}</span><h1>{challenge.title}</h1><p>Statut : <strong>{statusLabel(status)}</strong></p></div><strong className="time-badge"><Clock3 size={18}/>{formatDuration(challenge.duration)}</strong></div><p className="lead">{challenge.objective||challenge.description}</p>{challenge.materials?.length?<Section icon={<PackageCheck size={20}/>} title="Matériel"><ul className="detail-list">{challenge.materials.map(x=><li key={x}>{x}</li>)}</ul></Section>:null}{challenge.installation?.length?<Section title="Installation"><ol className="numbered-list">{challenge.installation.map(x=><li key={x}>{x}</li>)}</ol></Section>:null}{challenge.steps?.length?<Section title="Déroulement"><ol className="numbered-list">{challenge.steps.map(x=><li key={x}>{x}</li>)}</ol></Section>:null}<div className="instruction-box"><h3>Critères de réussite</h3>{(challenge.successCriteria||[]).map(x=><p key={x}>✓ {x}</p>)}</div><div className="timer-label">Chronomètre · maximum {formatDuration(challenge.duration)}</div><Timer seconds={challenge.duration}/><div className="result-actions"><button className="accent-button" onClick={()=>onStatus("success")}>✓ Défi réussi</button><button className="secondary" onClick={()=>onStatus("retry")}>À reprendre</button>{status!=="todo"&&<button className="secondary" onClick={()=>onStatus("todo")}>Réinitialiser</button>}</div></div></>}
function SkillsScreen({skills,onSelect}:{skills:HandlerSkill[],onSelect:(s:HandlerSkill)=>void}){return <><SimpleHeader eyebrow="FORMATION DU CONDUCTEUR" title="Compétences du conducteur" text="Développez vos habiletés pour mieux accompagner votre chien pendant ses recherches."/><section className="skill-intro"><GraduationCap size={32}/><div><strong>Un parcours parallèle aux défis du chien</strong><p>Les compétences affichées ici proviennent de Supabase.</p></div></section><section className="category-section"><h2>Niveau 1 · Fondations</h2><div className="skill-grid">{skills.map(skill=><button className="skill-card" key={skill.id} onClick={()=>onSelect(skill)}><div className="skill-card-top"><span className="number">{skill.id}</span><span className="video-status"><PlayCircle size={16}/> {skill.videoUrl?"Vidéo disponible":"Vidéo à venir"}</span></div><h3>{skill.title}</h3><p>{skill.description}</p></button>)}</div></section><section className="locked-level"><Lock size={24}/><div><strong>Niveau 2</strong><p>À débloquer dans la progression du conducteur.</p></div></section></>}
function SkillDetail({skill,onBack}:{skill:HandlerSkill,onBack:()=>void}){return <><button className="back" onClick={onBack}>← Retour aux compétences</button><div className="detail-card"><div className="detail-heading"><div><span className="pill">Compétence conducteur · Niveau {skill.level}</span><h1>{skill.title}</h1></div><GraduationCap size={34}/></div><p className="lead">{skill.objective}</p><section className="video-placeholder"><PlayCircle size={48}/><h3>Vidéo de démonstration</h3><p>{skill.videoUrl?"Vidéo disponible":"Vidéo à venir"}</p></section><Section icon={<Footprints size={20}/>} title="Exercice pratique"><ol className="numbered-list">{skill.practice.map(x=><li key={x}>{x}</li>)}</ol></Section><div className="instruction-box"><h3>Critères de maîtrise</h3>{skill.success.map(x=><p key={x}>✓ {x}</p>)}</div></div></>}
function ProgressScreen({progress,completed,total,statuses}:any){const retry=Object.values(statuses).filter(s=>s==="retry").length;return <><SimpleHeader eyebrow="MON PARCOURS" title="Progression"/><div className="grid"><article className="hero-card"><span className="pill">Niveau 1</span><div className="big-number">{progress}%</div><p>{completed} défis réussis sur {total}</p><div className="progress"><span style={{width:`${progress}%`}}/></div></article><article className="card"><h3>État des défis</h3><p>✓ {completed} réussis</p><p>↻ {retry} à reprendre</p><p>○ {total-completed-retry} à faire</p></article></div></>}
function LexiconScreen(){const words=[["Source","Endroit précis où se trouve l'odeur cible."],["Cache","Emplacement choisi pour placer l'odeur ou la nourriture."],["Conducteur","Personne qui accompagne le chien pendant la recherche."],["Odeur cible","Odeur que le chien a appris à rechercher."]];return <><SimpleHeader eyebrow="RÉFÉRENCE" title="Lexique"/><div className="lexicon-grid">{words.map(([w,d])=><article className="card" key={w}><h3>{w}</h3><p>{d}</p></article>)}</div></>}
function ProfileScreen(){return <><SimpleHeader eyebrow="PROFIL" title="Mon chien"/><div className="profile-card"><div className="dog-avatar">🐕</div><div><h2>Nova</h2><p>Profil de démonstration</p><p>Niveau 1 · Débutant</p></div></div></>}
function SimpleHeader({eyebrow,title,text}:{eyebrow:string,title:string,text?:string}){return <header className="page-header"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{text&&<p>{text}</p>}</header>}
function Section({title,icon,children}:{title:string,icon?:React.ReactNode,children:React.ReactNode}){return <section className="detail-section"><h3>{icon}{title}</h3>{children}</section>}
function formatDuration(s:number){const m=Math.floor(s/60),r=s%60;return r?`${m} min ${r} s`:`${m} min`}
function statusLabel(s:ChallengeStatus="todo"){return s==="success"?"Réussi":s==="retry"?"À reprendre":"À faire"}
