"use client";

import { useMemo, useState } from "react";
import { Home, Trophy, Target, Dog, Clock3, CheckCircle2, BookOpen, PackageCheck, BarChart3, Settings, LogOut, PawPrint, Flame, Star, ArrowRight, Lightbulb, GraduationCap, PlayCircle, Lock, Footprints } from "lucide-react";
import { challenges, Challenge } from "../data/challenges";
import Timer from "../components/Timer";

type Screen = "home" | "challenges" | "skills" | "weekly" | "ranking" | "profile" | "lexicon";
type ChallengeStatus = "todo" | "success" | "retry";
type StatusMap = Record<number, ChallengeStatus>;
const categories = ["Intérieur", "Extérieur", "Lieu public"] as const;

const handlerSkills = [
  { id: 1, level: 1, title: "Maniement de la laisse — recherche intérieure", description: "Apprendre à accompagner le chien avec une laisse souple sans influencer sa recherche ni bloquer ses déplacements.", objective: "Développer une manipulation fluide de la laisse afin de laisser au chien la liberté nécessaire pour résoudre la recherche.", video: null, practice: ["Préparer une petite zone de recherche intérieure sécuritaire.", "Garder suffisamment de longueur de laisse pour permettre au chien d'explorer.", "Éviter de tirer, raccourcir ou diriger la laisse vers la cache.", "Suivre le chien plutôt que le précéder et maintenir les mains calmes."], success: ["La laisse demeure majoritairement détendue.", "Le conducteur ne dirige pas le chien vers la source.", "Le chien peut changer de direction sans être bloqué par la laisse."] },
  { id: 2, level: 1, title: "Laisse et déplacements — recherche de contenants", description: "Apprendre à se déplacer autour d'une ligne ou de rangées de contenants sans guider involontairement le chien.", objective: "Coordonner la laisse, la position du corps et les déplacements du conducteur pendant une recherche de contenants.", video: null, practice: ["Installer plusieurs contenants en ligne ou en deux rangées.", "Donner au chien l'espace nécessaire pour inspecter chaque contenant.", "Se déplacer avec le chien sans passer devant lui ni pointer un contenant avec le corps.", "Gérer la laisse pour éviter qu'elle touche ou déplace les contenants."], success: ["Le conducteur suit le déplacement du chien avec fluidité.", "La laisse ne gêne pas l'inspection des contenants.", "Le positionnement du conducteur n'indique pas la position de la cible."] }
];

type HandlerSkill = typeof handlerSkills[number];

export default function Page() {
  const [screen, setScreen] = useState<Screen>("home");
  const [selected, setSelected] = useState<Challenge | null>(null);
  const [selectedSkill, setSelectedSkill] = useState<HandlerSkill | null>(null);
  const [statuses, setStatuses] = useState<StatusMap>(() => Object.fromEntries(challenges.map(c => [c.id, c.completed ? "success" : "todo"])) as StatusMap);
  const currentLevel = 1;
  const total = challenges.length;
  const completed = Object.values(statuses).filter(status => status === "success").length;
  const progress = Math.round((completed / total) * 100);
  const grouped = useMemo(() => categories.map(category => ({ category, items: challenges.filter(c => c.category === category) })), []);
  const go = (next: Screen) => { setScreen(next); setSelected(null); setSelectedSkill(null); };
  const setChallengeStatus = (id: number, status: ChallengeStatus) => setStatuses(current => ({ ...current, [id]: status }));

  return <main className="shell"><aside className="sidebar"><div className="brand-block brand-image-block"><img src="/brand-logo.jpg" alt="Sniff and Fun Challenge" className="sidebar-logo" /></div><nav>
    <NavButton active={screen === "home"} onClick={() => go("home")} icon={<Home size={19}/>} label="Accueil" />
    <NavButton active={screen === "challenges"} onClick={() => go("challenges")} icon={<Trophy size={19}/>} label="Défis" />
    <NavButton active={screen === "skills"} onClick={() => go("skills")} icon={<GraduationCap size={19}/>} label="Compétences conducteur" />
    <NavButton active={screen === "weekly"} onClick={() => go("weekly")} icon={<Target size={19}/>} label="Défi hebdomadaire" />
    <NavButton active={screen === "ranking"} onClick={() => go("ranking")} icon={<BarChart3 size={19}/>} label="Progression" />
    <NavButton active={screen === "lexicon"} onClick={() => go("lexicon")} icon={<BookOpen size={19}/>} label="Lexique" />
    <NavButton active={screen === "profile"} onClick={() => go("profile")} icon={<Dog size={19}/>} label="Profil" />
    <button className="nav-btn muted-nav" disabled><Settings size={19}/><span>Paramètres</span></button>
  </nav><div className="sidebar-profile"><div className="avatar">🐕</div><div><strong>Nova</strong><span>Niveau {currentLevel}</span></div><div className="mini-progress"><span style={{width:`${progress}%`}}/></div></div><button className="logout" disabled><LogOut size={18}/> Déconnexion</button></aside>

  <section className="content">{selected ? <ChallengeDetail challenge={selected} status={statuses[selected.id] || "todo"} onStatusChange={status => setChallengeStatus(selected.id, status)} onBack={() => setSelected(null)} />
    : selectedSkill ? <HandlerSkillDetail skill={selectedSkill} onBack={() => setSelectedSkill(null)} />
    : screen === "home" ? <HomeScreen progress={progress} completed={completed} total={total} statuses={statuses} onChallenges={() => go("challenges")} onSelect={setSelected} />
    : screen === "challenges" ? <ChallengesScreen grouped={grouped} statuses={statuses} onSelect={setSelected} />
    : screen === "skills" ? <HandlerSkillsScreen onSelect={setSelectedSkill} />
    : screen === "weekly" ? <WeeklyScreen /> : screen === "ranking" ? <ProgressScreen progress={progress} completed={completed} total={total} statuses={statuses} /> : screen === "lexicon" ? <LexiconScreen /> : <ProfileScreen />}</section></main>;
}

function NavButton({active,onClick,icon,label}:any){return <button className={`nav-btn ${active?"active":""}`} onClick={onClick}>{icon}<span>{label}</span></button>}

function HomeScreen({progress,completed,total,statuses,onChallenges,onSelect}:any){const featured=challenges.slice(0,2);return <div className="dashboard"><section className="brand-hero sniff-fun-hero"><img src="/sniff-fun-hero.jpg" alt="Sniff and Fun Challenge"/><div className="hero-copy hero-copy-light"><div className="hero-brand-name">Sniff and Fun <span>Challenge</span></div><h1>Défi de détection d’odeurs<br/>pour chiens.</h1><p>Des défis progressifs, simples et motivants à pratiquer à la maison avec votre chien.</p><button className="accent-button" onClick={onChallenges}>Commencer un défi</button></div></section><section className="welcome-strip"><div className="welcome-icon"><PawPrint size={28}/></div><div><h2>Bonjour !</h2><p>Prêt pour une nouvelle aventure olfactive avec votre chien ?</p></div><div className="quick-stats"><div><Flame size={25}/><span><small>Série actuelle</small><strong>5 jours</strong></span></div><div><Star size={25}/><span><small>Défis réussis</small><strong>{completed}</strong></span></div></div></section><div className="dashboard-grid"><section className="panel available-panel"><div className="panel-heading"><div><p className="eyebrow">À PRATIQUER</p><h2>Défis disponibles</h2></div><button className="text-link" onClick={onChallenges}>Voir tous <ArrowRight size={16}/></button></div><div className="featured-grid">{featured.map((c:Challenge)=><article className="featured-card" key={c.id}><div className={`featured-image image-${c.id}`}><span>NIVEAU 1</span><div className="scene-icon">{c.id===1?"🚪🐕":"🪑🐕"}</div></div><div className="featured-body"><h3>{c.title}</h3><p>{c.description}</p><div className="featured-footer"><span><Trophy size={16}/>{statusLabel(statuses[c.id])}</span><button className="accent-button small" onClick={()=>onSelect(c)}>{statuses[c.id]==="success"?"Revoir":"Commencer"}</button></div></div></article>)}</div></section><section className="panel progress-panel"><div className="panel-heading"><div><p className="eyebrow">PARCOURS</p><h2>Ma progression</h2></div></div><div className="progress-layout"><div className="progress-ring" style={{"--pct":`${progress*3.6}deg`} as React.CSSProperties}><div><small>NIVEAU</small><strong>1</strong><span>{completed}/{total} défis</span></div></div><div className="progress-list"><p><Trophy size={18}/><span>Défis réussis</span><strong>{completed}</strong></p><p><Clock3 size={18}/><span>Temps d'entraînement</span><strong>—</strong></p><p><CheckCircle2 size={18}/><span>Progression</span><strong>{progress}%</strong></p><p><Flame size={18}/><span>Meilleure série</span><strong>5 jours</strong></p></div></div><button className="green-button wide" onClick={onChallenges}>Voir mes défis</button></section></div><section className="tip-strip"><div className="tip-icon"><Lightbulb size={26}/></div><div><h3>Conseil du jour</h3><p>Laisse ton chien prendre son temps et suivre son nez. Chaque réussite renforce sa confiance !</p></div></section></div>}

function HandlerSkillsScreen({onSelect}:{onSelect:(skill:HandlerSkill)=>void}){return <><header className="page-header"><p className="eyebrow">FORMATION DU CONDUCTEUR</p><h1>Compétences du conducteur</h1><p>Développez vos propres habiletés pour mieux accompagner votre chien pendant ses recherches.</p></header><section className="skill-intro"><GraduationCap size={32}/><div><strong>Un parcours en parallèle des défis du chien</strong><p>Chaque niveau comprend des techniques à apprendre, une démonstration vidéo et un exercice pratique. Les vidéos pourront être ajoutées plus tard depuis l'espace administrateur.</p></div></section><section className="category-section"><h2>Niveau 1 · Fondations</h2><div className="skill-grid">{handlerSkills.map(skill=><button className="skill-card" key={skill.id} onClick={()=>onSelect(skill)}><div className="skill-card-top"><span className="number">{skill.id}</span><span className="video-status"><PlayCircle size={16}/> Vidéo à venir</span></div><div className="skill-icon">{skill.id===1?"🦮":"📦"}</div><h3>{skill.title}</h3><p>{skill.description}</p><span className="skill-open">Voir la compétence <ArrowRight size={16}/></span></button>)}</div></section><section className="locked-level"><Lock size={24}/><div><strong>Niveau 2</strong><p>Les compétences plus avancées seront ajoutées et débloquées dans la progression du conducteur.</p></div></section></>}

function HandlerSkillDetail({skill,onBack}:{skill:HandlerSkill,onBack:()=>void}){return <><button className="back" onClick={onBack}>← Retour aux compétences</button><div className="detail-card skill-detail"><div className="detail-heading"><div><span className="pill">Compétence conducteur · Niveau {skill.level}</span><h1>{skill.title}</h1></div><GraduationCap size={34}/></div><p className="lead">{skill.objective}</p><section className="video-placeholder"><PlayCircle size={48}/><h3>Vidéo de démonstration</h3><p>Vidéo à venir</p><small>Cet emplacement est prêt à recevoir la vidéo lorsque vous souhaiterez l'ajouter.</small></section><DetailSection icon={<Footprints size={20}/>} title="Exercice pratique"><ol className="numbered-list">{skill.practice.map(item=><li key={item}>{item}</li>)}</ol></DetailSection><div className="instruction-box"><h3>Critères de maîtrise</h3>{skill.success.map(item=><p key={item}>✓ {item}</p>)}</div><div className="skill-note"><strong>À venir :</strong> cette compétence pourra avoir son propre statut « maîtrisée » et contribuer au déverrouillage des niveaux du conducteur.</div></div></>}

function ChallengesScreen({grouped,statuses,onSelect}:any){return <><header className="page-header"><p className="eyebrow">NIVEAU 1</p><h1>Mes défis</h1><p>Complète toutes les catégories pour débloquer le niveau suivant.</p></header>{grouped.map((g:any)=><section key={g.category} className="category-section"><h2>{g.category}</h2><div className="challenge-grid">{g.items.map((c:Challenge)=><button className={`challenge-card challenge-${statuses[c.id]}`} key={c.id} onClick={()=>onSelect(c)}><div className="challenge-top"><span className="number">{c.id}</span>{statuses[c.id]==="success"?<CheckCircle2 size={20} className="done"/>:<span className="status">{statusLabel(statuses[c.id])}</span>}</div><h3>{c.title}</h3><p>{c.description}</p><small>{formatDuration(c.duration)} max</small></button>)}</div></section>)}</>}
function ChallengeDetail({challenge,status,onStatusChange,onBack}:{challenge:Challenge,status:ChallengeStatus,onStatusChange:(s:ChallengeStatus)=>void,onBack:()=>void}){return <><button className="back" onClick={onBack}>← Retour aux défis</button><div className="detail-card"><div className="detail-heading"><div><span className="pill">{challenge.category} · Niveau {challenge.level}</span><h1>{challenge.title}</h1><p>Statut : <strong>{statusLabel(status)}</strong></p></div><strong className="time-badge"><Clock3 size={18}/>{formatDuration(challenge.duration)}</strong></div><p className="lead">{challenge.objective||challenge.description}</p>{challenge.materials&&<DetailSection icon={<PackageCheck size={20}/>} title="Matériel"><ul className="detail-list">{challenge.materials.map(i=><li key={i}>{i}</li>)}</ul></DetailSection>}{challenge.installation&&<DetailSection title="Installation"><ol className="numbered-list">{challenge.installation.map(i=><li key={i}>{i}</li>)}</ol></DetailSection>}{challenge.steps&&<DetailSection title="Déroulement"><ol className="numbered-list">{challenge.steps.map(i=><li key={i}>{i}</li>)}</ol></DetailSection>}<div className="instruction-box"><h3>Critères de réussite</h3>{(challenge.successCriteria||["Le chien identifie correctement la cache."]).map(i=><p key={i}>✓ {i}</p>)}</div><div className="timer-label">Chronomètre · maximum {formatDuration(challenge.duration)}</div><Timer seconds={challenge.duration}/><div className="result-actions"><button className="accent-button" onClick={()=>onStatusChange("success")}>✓ Défi réussi</button><button className="secondary" onClick={()=>onStatusChange("retry")}>À reprendre</button>{status!=="todo"&&<button className="secondary" onClick={()=>onStatusChange("todo")}>Réinitialiser</button>}</div>{status!=="todo"&&<div className={`result-message ${status==="success"?"success":"retry"}`}>{status==="success"?"Bravo ! La progression a été mise à jour pour cette session.":"Ce défi est marqué à reprendre."}</div>}</div></>}
function DetailSection({title,icon,children}:{title:string,icon?:React.ReactNode,children:React.ReactNode}){return <section className="detail-section"><h3>{icon}{title}</h3>{children}</section>}
function formatDuration(s:number){const m=Math.floor(s/60),r=s%60;return r?`${m} min ${r} s`:`${m} min`}
function statusLabel(s:ChallengeStatus="todo"){return s==="success"?"Réussi":s==="retry"?"À reprendre":"À faire"}
function ProgressScreen({progress,completed,total,statuses}:any){const retry=Object.values(statuses).filter(s=>s==="retry").length;return <><header className="page-header"><p className="eyebrow">MON PARCOURS</p><h1>Progression</h1></header><div className="grid"><article className="hero-card"><span className="pill">Niveau 1</span><h2>Progression générale</h2><div className="big-number">{progress}%</div><p>{completed} défis réussis sur {total}</p><div className="progress"><span style={{width:`${progress}%`}}/></div></article><article className="card"><h3>État des défis</h3><p>✓ {completed} réussis</p><p>↻ {retry} à reprendre</p><p>○ {total-completed-retry} à faire</p></article></div></>}
function LexiconScreen(){const words=[["Source","Endroit précis où se trouve l'odeur cible."],["Cache","Emplacement choisi pour placer l'odeur ou la nourriture pendant l'exercice."],["Conducteur","Personne qui accompagne le chien pendant la recherche."],["Marquer verbalement","Utiliser un mot précis, par exemple « YES », lorsque le chien trouve la source."],["Leurrer","Guider temporairement le chien avec une récompense pour l'éloigner de la source."],["Odeur cible","Odeur que le chien a appris à rechercher et à identifier."]];return <><header className="page-header"><p className="eyebrow">RÉFÉRENCE</p><h1>Lexique</h1></header><div className="lexicon-grid">{words.map(([w,d])=><article className="card" key={w}><h3>{w}</h3><p className="muted">{d}</p></article>)}</div></>}
function WeeklyScreen(){return <><header className="page-header"><p className="eyebrow">CETTE SEMAINE</p><h1>Défi hebdomadaire · Niveau 1</h1><p>Trois recherches à compléter pour participer au classement.</p></header></>}
function ProfileScreen(){return <><header className="page-header"><p className="eyebrow">PROFIL</p><h1>Mon chien</h1></header><div className="profile-card"><div className="dog-avatar">🐕</div><div><h2>Nova</h2><p>Profil de démonstration</p><p>Niveau 1 · Débutant</p></div></div></>}
